{
  "meta": {
    "baseUrl": "https://dependencytrack.example.com",
    "application": "Dependency-Track",
    "version": "4.10.1",
    "timestamp": "2024-02-03T09:59:36Z"
  },
  "findings": [
    {
      "component": {
        "name": "GitPython",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/gitpython@3.1.40",
        "uuid": "85b9f10b-23b6-45f4-92ea-c84ccc21855b",
        "version": "3.1.40",
        "latestVersion": "3.1.41"
      },
      "attribution": {
        "analyzerIdentity": "INTERNAL_ANALYZER",
        "attributedOn": "2024-01-31 15:19:43.851"
      },
      "vulnerability": {
        "severity": "HIGH",
        "severityRank": 1,
        "cweName": "Untrusted Search Path",
        "vulnId": "GHSA-2mqj-m65w-jghx",
        "aliases": [
          {
            "ghsaId": "GHSA-2mqj-m65w-jghx",
            "cveId": "CVE-2024-22190"
          }
        ],
        "cweId": 426,
        "description": "### Summary\n\nThis issue exists because of an incomplete fix for CVE-2023-40590. On Windows, GitPython uses an untrusted search path if it uses a shell to run `git`, as well as when it runs `bash.exe` to interpret hooks. If either of those features are used on Windows, a malicious `git.exe` or `bash.exe` may be run from an untrusted repository.\n\n### Details\n\nAlthough GitPython often avoids executing programs found in an untrusted search path since 3.1.33, two situations remain where this still occurs. Either can allow arbitrary code execution under some circumstances.\n\n#### When a shell is used\n\nGitPython can be told to run `git` commands through a shell rather than as direct subprocesses, by passing `shell=True` to any method that accepts it, or by both setting `Git.USE_SHELL = True` and not passing `shell=False`. Then the Windows `cmd.exe` shell process performs the path search, and GitPython does not prevent that shell from finding and running `git` in the current directory.\n\nWhen GitPython runs `git` directly rather than through a shell, the GitPython process performs the path search, and currently omits the current directory by setting `NoDefaultCurrentDirectoryInExePath` in its own environment during the `Popen` call. Although the `cmd.exe` shell will honor this environment variable when present, GitPython does not currently pass it into the shell subprocess's environment.\n\nFurthermore, because GitPython sets the subprocess CWD to the root of a repository's working tree, using a shell will run a malicious `git.exe` in an untrusted repository even if GitPython itself is run from a trusted location.\n\nThis also applies if `Git.execute` is called directly with `shell=True` (or after `Git.USE_SHELL = True`) to run any command.\n\n#### When hook scripts are run\n\nOn Windows, GitPython uses `bash.exe` to run hooks that appear to be scripts. However, unlike when running `git`, no steps are taken to avoid finding and running `bash.exe` in the current directory.\n\nThis allows the author of an untrusted fork or branch to cause a malicious `bash.exe` to be run in some otherwise safe workflows. An example of such a scenario is if the user installs a trusted hook while on a trusted branch, then switches to an untrusted feature branch (possibly from a fork) to review proposed changes. If the untrusted feature branch contains a malicious `bash.exe` and the user's current working directory is the working tree, and the user performs an action that runs the hook, then although the hook itself is uncorrupted, it runs with the malicious `bash.exe`.\n\nNote that, while `bash.exe` is a shell, this is a separate scenario from when `git` is run using the unrelated Windows `cmd.exe` shell.\n\n### PoC\n\nOn Windows, create a `git.exe` file in a repository. Then create a `Repo` object, and call any method through it (directly or indirectly) that supports the `shell` keyword argument with `shell=True`:\n\n```powershell\nmkdir testrepo\ngit init testrepo\ncp ... testrepo git.exe # Replace \"...\" with any executable of choice.\npython -c \"import git; print(git.Repo('testrepo').git.version(shell=True))\"\n```\n\nThe `git.exe` executable in the repository directory will be run.\n\nOr use no `Repo` object, but do it from the location with the `git.exe`:\n\n```powershell\ncd testrepo\npython -c \"import git; print(git.Git().version(shell=True))\"\n```\n\nThe `git.exe` executable in the current directory will be run.\n\nFor the scenario with hooks, install a hook in a repository, create a `bash.exe` file in the current directory, and perform an operation that causes GitPython to attempt to run the hook:\n\n```powershell\nmkdir testrepo\ncd testrepo\ngit init\nmv .git/hooks/pre-commit.sample .git/hooks/pre-commit\ncp ... bash.exe # Replace \"...\" with any executable of choice.\necho \"Some text\" >file.txt\ngit add file.txt\npython -c \"import git; git.Repo().index.commit('Some message')\"\n```\n\nThe `bash.exe` executable in the current directory will be run.\n\n### Impact\n\nThe greatest impact is probably in applications that set `Git.USE_SHELL = True` for historical reasons. (Undesired console windows had, in the past, been created in some kinds of applications, when it was not used.) Such an application may be vulnerable to arbitrary code execution from a malicious repository, even with no other exacerbating conditions. This is to say that, if a shell is used to run `git`, the full effect of CVE-2023-40590 is still present. Furthermore, as noted above, running the application itself from a trusted directory is not a sufficient mitigation.\n\nAn application that does not direct GitPython to use a shell to run `git` subprocesses thus avoids most of the risk. However, there is no such straightforward way to prevent GitPython from running `bash.exe` to interpret hooks. So while the conditions needed for that to be exploited are more involved, it may be harder to mitigate decisively prior to patching.\n\n### Possible solutions\n\nA straightforward approach would be to address each bug directly:\n\n- When a shell is used, pass `NoDefaultCurrentDirectoryInExePath` into the subprocess environment, because in that scenario the subprocess is the `cmd.exe` shell that itself performs the path search.\n- Set `NoDefaultCurrentDirectoryInExePath` in the GitPython process environment during the `Popen` call made to run hooks with a `bash.exe` subprocess.\n\nThese need only be done on Windows.",
        "source": "GITHUB",
        "title": "Untrusted search path under some conditions on Windows allows arbitrary code execution",
        "cwes": [
          {
            "cweId": 426,
            "name": "Untrusted Search Path",
            "id": 0
          }
        ],
        "uuid": "16cd5a0e-26d7-4a99-b1cf-5e905cd35e6c"
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:85b9f10b-23b6-45f4-92ea-c84ccc21855b:16cd5a0e-26d7-4a99-b1cf-5e905cd35e6c"
    },
    {
      "component": {
        "name": "urllib3",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/urllib3@1.26.16",
        "uuid": "4b5385f9-52fa-4116-a6e8-79197ad27c01",
        "version": "1.26.16",
        "latestVersion": "2.2.0"
      },
      "attribution": {
        "analyzerIdentity": "INTERNAL_ANALYZER",
        "attributedOn": "2024-01-31 15:19:44.097"
      },
      "vulnerability": {
        "severity": "MEDIUM",
        "severityRank": 2,
        "cweName": "Exposure of Sensitive Information to an Unauthorized Actor",
        "vulnId": "GHSA-v845-jxx5-vc9f",
        "aliases": [
          {
            "ghsaId": "GHSA-v845-jxx5-vc9f",
            "cveId": "CVE-2023-43804"
          }
        ],
        "cweId": 200,
        "description": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
        "source": "GITHUB",
        "title": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
        "cwes": [
          {
            "cweId": 200,
            "name": "Exposure of Sensitive Information to an Unauthorized Actor",
            "id": 0
          }
        ],
        "uuid": "5d7499f1-fb73-4100-a45a-63c9adc4b5f6"
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:4b5385f9-52fa-4116-a6e8-79197ad27c01:5d7499f1-fb73-4100-a45a-63c9adc4b5f6"
    },
    {
      "component": {
        "name": "urllib3",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/urllib3@1.26.16",
        "uuid": "4b5385f9-52fa-4116-a6e8-79197ad27c01",
        "version": "1.26.16",
        "latestVersion": "2.2.0"
      },
      "attribution": {
        "analyzerIdentity": "INTERNAL_ANALYZER",
        "attributedOn": "2024-01-31 15:19:44.145"
      },
      "vulnerability": {
        "severity": "MEDIUM",
        "severityRank": 2,
        "cweName": "Exposure of Sensitive Information to an Unauthorized Actor",
        "vulnId": "GHSA-g4mx-q9vg-27p4",
        "aliases": [
          {
            "ghsaId": "GHSA-g4mx-q9vg-27p4",
            "cveId": "CVE-2023-45803"
          }
        ],
        "cweId": 200,
        "description": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.\n",
        "source": "GITHUB",
        "title": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
        "cwes": [
          {
            "cweId": 200,
            "name": "Exposure of Sensitive Information to an Unauthorized Actor",
            "id": 0
          }
        ],
        "uuid": "efd2b264-3475-4555-bf59-ff149b8dcc1f"
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:4b5385f9-52fa-4116-a6e8-79197ad27c01:efd2b264-3475-4555-bf59-ff149b8dcc1f"
    },
    {
      "component": {
        "name": "GitPython",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/gitpython@3.1.40",
        "uuid": "85b9f10b-23b6-45f4-92ea-c84ccc21855b",
        "version": "3.1.40",
        "latestVersion": "3.1.41"
      },
      "attribution": {
        "alternateIdentifier": "CVE-2024-22190",
        "analyzerIdentity": "OSSINDEX_ANALYZER",
        "attributedOn": "2024-01-31 15:19:45.314",
        "referenceUrl": "https://ossindex.sonatype.org/vulnerability/CVE-2024-22190?component-type=pypi&component-name=gitpython&utm_source=dependency-track&utm_medium=integration&utm_content=v4.10.1"
      },
      "vulnerability": {
        "severity": "HIGH",
        "cvssV3BaseScore": 7.8,
        "vulnId": "CVE-2024-22190",
        "aliases": [
          {
            "ghsaId": "GHSA-2mqj-m65w-jghx",
            "cveId": "CVE-2024-22190"
          }
        ],
        "cweId": 426,
        "description": "GitPython is a python library used to interact with Git repositories. There is an incomplete fix for CVE-2023-40590. On Windows, GitPython uses an untrusted search path if it uses a shell to run `git`, as well as when it runs `bash.exe` to interpret hooks. If either of those features are used on Windows, a malicious `git.exe` or `bash.exe` may be run from an untrusted repository. This issue has been patched in version 3.1.41.",
        "epssScore": 0.0005,
        "source": "NVD",
        "cwes": [
          {
            "cweId": 426,
            "name": "Untrusted Search Path",
            "id": 0
          }
        ],
        "uuid": "fc537a1b-c02e-43e8-85c8-d3bb0df657e9",
        "severityRank": 1,
        "cweName": "Untrusted Search Path",
        "epssPercentile": 0.16806
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:85b9f10b-23b6-45f4-92ea-c84ccc21855b:fc537a1b-c02e-43e8-85c8-d3bb0df657e9"
    },
    {
      "component": {
        "name": "pandas",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/pandas@2.1.4",
        "uuid": "23076602-7400-49e8-8323-71bd976c882c",
        "version": "2.1.4",
        "latestVersion": "2.2.0"
      },
      "attribution": {
        "alternateIdentifier": "CVE-2020-13091",
        "analyzerIdentity": "OSSINDEX_ANALYZER",
        "attributedOn": "2024-01-31 15:19:45.691",
        "referenceUrl": "https://ossindex.sonatype.org/vulnerability/CVE-2020-13091?component-type=pypi&component-name=pandas&utm_source=dependency-track&utm_medium=integration&utm_content=v4.10.1"
      },
      "vulnerability": {
        "severity": "CRITICAL",
        "cvssV3BaseScore": 9.8,
        "vulnId": "CVE-2020-13091",
        "aliases": [],
        "cweId": 502,
        "description": "pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner",
        "epssScore": 0.00996,
        "source": "NVD",
        "cwes": [
          {
            "cweId": 502,
            "name": "Deserialization of Untrusted Data",
            "id": 0
          }
        ],
        "uuid": "93fb366a-ed84-4a4a-957c-7a1e68ef0fb3",
        "severityRank": 0,
        "cweName": "Deserialization of Untrusted Data",
        "epssPercentile": 0.82016,
        "cvssV2BaseScore": 7.5
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:23076602-7400-49e8-8323-71bd976c882c:93fb366a-ed84-4a4a-957c-7a1e68ef0fb3"
    },
    {
      "component": {
        "name": "urllib3",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/urllib3@1.26.16",
        "uuid": "4b5385f9-52fa-4116-a6e8-79197ad27c01",
        "version": "1.26.16",
        "latestVersion": "2.2.0"
      },
      "attribution": {
        "alternateIdentifier": "CVE-2023-43804",
        "analyzerIdentity": "OSSINDEX_ANALYZER",
        "attributedOn": "2024-01-31 15:19:45.919",
        "referenceUrl": "https://ossindex.sonatype.org/vulnerability/CVE-2023-43804?component-type=pypi&component-name=urllib3&utm_source=dependency-track&utm_medium=integration&utm_content=v4.10.1"
      },
      "vulnerability": {
        "severity": "HIGH",
        "cvssV3BaseScore": 8.1,
        "vulnId": "CVE-2023-43804",
        "aliases": [
          {
            "ghsaId": "GHSA-v845-jxx5-vc9f",
            "cveId": "CVE-2023-43804"
          }
        ],
        "cweId": 200,
        "description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.",
        "epssScore": 0.00102,
        "source": "NVD",
        "cwes": [
          {
            "cweId": 200,
            "name": "Exposure of Sensitive Information to an Unauthorized Actor",
            "id": 0
          }
        ],
        "uuid": "6420ff6f-9226-4e68-b695-6f0326a49ea2",
        "severityRank": 1,
        "cweName": "Exposure of Sensitive Information to an Unauthorized Actor",
        "epssPercentile": 0.41552
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:4b5385f9-52fa-4116-a6e8-79197ad27c01:6420ff6f-9226-4e68-b695-6f0326a49ea2"
    },
    {
      "component": {
        "name": "urllib3",
        "project": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
        "purl": "pkg:pypi/urllib3@1.26.16",
        "uuid": "4b5385f9-52fa-4116-a6e8-79197ad27c01",
        "version": "1.26.16",
        "latestVersion": "2.2.0"
      },
      "attribution": {
        "alternateIdentifier": "CVE-2023-45803",
        "analyzerIdentity": "OSSINDEX_ANALYZER",
        "attributedOn": "2024-01-31 15:19:45.978",
        "referenceUrl": "https://ossindex.sonatype.org/vulnerability/CVE-2023-45803?component-type=pypi&component-name=urllib3&utm_source=dependency-track&utm_medium=integration&utm_content=v4.10.1"
      },
      "vulnerability": {
        "severity": "MEDIUM",
        "cvssV3BaseScore": 4.2,
        "vulnId": "CVE-2023-45803",
        "aliases": [
          {
            "ghsaId": "GHSA-g4mx-q9vg-27p4",
            "cveId": "CVE-2023-45803"
          }
        ],
        "cweId": 200,
        "description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.\n",
        "epssScore": 0.00043,
        "source": "NVD",
        "cwes": [
          {
            "cweId": 200,
            "name": "Exposure of Sensitive Information to an Unauthorized Actor",
            "id": 0
          }
        ],
        "uuid": "3ef52aaa-6f61-4b8e-9764-d51fe5cd754d",
        "severityRank": 2,
        "cweName": "Exposure of Sensitive Information to an Unauthorized Actor",
        "epssPercentile": 0.07756
      },
      "analysis": {
        "isSuppressed": false
      },
      "matrix": "1g2345tc-16rh-7te5-92b5-12345z6789fb:4b5385f9-52fa-4116-a6e8-79197ad27c01:3ef52aaa-6f61-4b8e-9764-d51fe5cd754d"
    }
  ],
  "project": {
    "name": "blablabla-Requirements-txt",
    "uuid": "1g2345tc-16rh-7te5-92b5-12345z6789fb",
    "version": "1"
  },
  "version": "1.2"
}